# Generated by Django 5.2.1 on 2025-06-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('en_mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20),
        ),
    ]
