# Generated by Django 4.2.23 on 2025-06-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_box_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible')], default='Disponible', max_length=20),
        ),
    ]
