# Generated by Django 4.2.23 on 2025-06-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_especialista_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaEspecialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialista', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('horario_disponible', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible')], default='Disponible', max_length=20)),
            ],
        ),
    ]
