version: '3.8'

services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password  # ¡Importante!
    environment:
      MYSQL_ROOT_PASSWORD: adminredsalud
      MYSQL_DATABASE: redsalud_db
      MYSQL_USER: redsalud_user
      MYSQL_PASSWORD: redsalud
    ports:
      - "3307:3306"  # Solo si necesitas acceder desde tu máquina local
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:  # Verifica si MySQL está listo
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  backend:
    build: ./backend
    command: sh -c "while ! (timeout 1 bash -c 'cat < /dev/null > /dev/tcp/db/3306') 2>/dev/null; do sleep 2; done; python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_NAME: redsalud_db  # Estos deben coincidir con settings.py
      DATABASE_USER: redsalud_user
      DATABASE_PASSWORD: redsalud
      DATABASE_HOST: db        

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  db_data:
  node_modules:

  