version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: adminredsalud
      MYSQL_DATABASE: redsalud_db
      MYSQL_USER: redsalud_user
      MYSQL_PASSWORD: redsalud
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    command: sh -c "sleep 5 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: redsalud_db
      DATABASE_USER: django_user
      DATABASE_PASSWORD: django_password

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  db_data:
  node_modules:

  